# Generated by Django 2.2.3 on 2022-08-12 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0006_auto_20220804_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=12, unique=True)),
                ('equipo', models.CharField(max_length=20, unique=True)),
                ('cliente', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='año_compra',
            new_name='fecha_compra',
        ),
        migrations.RenameField(
            model_name='assets',
            old_name='id',
            new_name='id_asset',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='clientes',
            name='asset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proyectoinventario.Assets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assets',
            name='serie',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
