# Generated by Django 2.2.3 on 2022-08-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0007_auto_20220811_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
