# Generated by Django 2.2.3 on 2022-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0008_auto_20220811_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='equipo',
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipo', models.CharField(max_length=20, unique=True)),
                ('cliente', models.CharField(max_length=30)),
                ('ip', models.ForeignKey(on_delete='cascade', to='proyectoinventario.Ip')),
            ],
        ),
    ]
