# Generated by Django 2.2.3 on 2022-08-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0010_auto_20220812_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(max_length=12),
        ),
    ]
