# Generated by Django 2.2.3 on 2022-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0011_auto_20220812_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='equipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
