# Generated by Django 2.2.3 on 2022-08-09 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0012_auto_20220805_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='id',
            new_name='id_asset',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoinventario.Assets', to_field='id'),
        ),
    ]
