# Generated by Django 2.2.3 on 2022-08-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoinventario', '0016_auto_20220809_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='cantidad',
        ),
    ]
